apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  labels:
    app: sample-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-deployment
  template:
    metadata:
      labels:
        app: sample-app-deployment
    spec:
      containers:
        - name: sample
          image: sample-app:1.0
          ports:
            - name: sample-port
              containerPort: 8080
